export enum Paises {
    "EEUU" = 1,
    "China" = 2,
    "Nigeria" = 3,
    "Camerun" = 4,
    "Colombia" = 5,
    "Peru" = 6,
    "Ecuador" = 7,
    "Bolivia" = 8,
    "Guatemala" = 9,
    "Honduras" = 10,
    "El Salvador" = 11,
    "Nicaragua" = 12,
    "Costa Rica" = 13,
    "Panama" = 14,
}
